### ISSUE TITLE
❓UpsertRequest

### ISSUE THREAD

**Issue by luskin** [Stedi/typesuite#372]
Has anybody found a way to create an `UpsertRequest`? From other comments in other PRs the maintainers have stated that the client can functionaly write to NetSuite but there is no documentation yet. When I inspect the types, however, I do not find this to be true. Any advice?

**Comment by dkanter14** [comment]
Hey @luskin - thanks for reaching out. A member of our engineering team tried this out, and it seems to work. I have added a code snippet at the bottom of this note. 

That being said, I wanted to be transparent in that we are no longer supporting this project or making changes. We are starting to use the new NetSuite REST API ([docs](https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/chapter_1540391670.html)) for our new integrations. We are going to adjust the README to indicate the current status of the project.

Separately, we do have several engineers with a ton of NetSuite experience here (we run our internal operations on NetSuite, and our largest customer runs on NetSuite), so we'd be happy to schedule a call and do some knowledge sharing if that would be useful for you all. We are building an EDI & integrations platform (across all industries like freight, retail, insurance, etc), so we'd be very excited to meet! 

--

**This might help you!**
```
const credentials = CREDS;
  const client = new TypeSuiteClient({
    account: credentials.account,
    apiVersion: "2019_2",
    token: {
      consumerKey: credentials.consumer_key,
      consumerSecret: credentials.consumer_secret,
      tokenKey: credentials.token_key,
      tokenSecret: credentials.token_secret,
    },
    preferences: {
      ignoreReadOnlyFields: true,
    },
  });

  const newPO: PurchaseOrder = new PurchaseOrder({
    externalId: "badccd48-1bab-4e18-b3a9-9c9af3c00d79"
    // ... more stuff here
  });
  const request = new UpsertRequest({
    record: newPO,
  });
  const response = await client.upsert(request);
```

**Comment by luskin** [comment]
Hi @dkanter14. Thank you this has been **_extremely_** helpful. We are deep in our NetSuite integration at the moment and, unfortunately, had to switch from REST from SOAP after discovering that many of the records we need to interact with have known issues (i.e. Customer Payment & Vendor Payment). I have actually put my integrations team on taking a look at your business as we are exploring EDI at the moment. Please reach out to me directly at gregg@mothership.com and let's set up a call. Thanks again!

**Comment by dkanter14** [comment]
Will send you a note, @luskin! And yes, we also have anecdotes for needing to switch back to SOAP for a number of reasons. I will check with the team on your request!
